language: node_js
node_js:
  - "node"
dist: trusty
install:
  - npm ci             
script:
  - "travis_wait 30"
  - "export NODE_ENV=test"
  - "npm run build"
  - "npm run test"
  - "npm run lint"
notifications:
  email: "false"