language: node_js
node_js:
  - "node"
install: "true"
script:
  - "travis_wait 30 sleep 1800"
  - "export NODE_ENV=test"
  - "npm run build"
  - "npm run test"
  - "npm run lint"
notifications:
  email: "false"