language: node_js
node_js:
  - "node"
dist: "trusty"
script:
  - "export NODE_ENV=test"
  - "npm run build"
  - "npm run test"
  - "npm run lint"
notifications:
  email: "false"
install:
  -"travis_wait 30"