language: node_js
node_js:
 - "node"
dist: "trusty"
cache:
directories:
- "node_modules"

services:
- postgresql

before_script:
- psql -c 'create database "store-manager-test";' -U postgres
- npm run postdeploy
script:
 - "export NODE_ENV=test"
 - "npm run build"
 - "npm run test"
after_success:
- npm run coveralls
- ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT