language: node_js
node_js:
  - "node"
dist: "trusty"
script:
  - "travis_wait 30 npm test"
  - "export NODE_ENV=test"
  - "npm run build"
  - "npm run test"
  - "npm run lint"
notifications:
  email: "false"
script:	script:
- 